apiVersion: skaffold/v2beta26
kind: Config

build:
  artifacts:
  - image: fastapi-sample
    context: .
    docker:
      dockerfile: containers/fastapi/Dockerfile

deploy:
  kubectl:
    manifests:
    - manifest/deployment.yaml