apiVersion: skaffold/v2beta26
kind: Config

build:
  artifacts:
  - image: backend-a
    context: .
    docker:
      dockerfile: containers/service-backend-a/Dockerfile
  - image: backend-b
    context: .
    docker:
      dockerfile: containers/service-backend-b/Dockerfile

deploy:
  kubectl:
    manifests:
    - manifest/service-backend-a.yaml
    - manifest/service-backend-b.yaml