apiVersion: skaffold/v2beta26
kind: Config

build:
  artifacts:
  - image: backend-a
    context: .
    docker:
      dockerfile: containers/service-backend-a/Dockerfile
  - image: backend-b
    context: .
    docker:
      dockerfile: containers/service-backend-b/Dockerfile
  - image: backend-for-frontend
    context: .
    docker:
      dockerfile: containers/service-backend-for-frontend/Dockerfile
  - image: otel-collector
    context: .
    docker:
      dockerfile: containers/opentelemetry-collector/Dockerfile

deploy:
  kubectl:
    manifests:
    - manifests/service-backend-for-frontend.yaml
    - manifests/service-backend-a.yaml
    - manifests/service-backend-b.yaml
    - manifests/opentelemetry-collector.yaml