kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000
    hostPort: 8080
  - containerPort: 30001
    hostPort: 8081
  - containerPort: 30002
    hostPort: 8082
  - containerPort: 30003
    hostPort: 4317
  - containerPort: 30004
    hostPort: 5080
- role: worker
  extraMounts:
  - containerPath: /mnt
    hostPath: ./
- role: worker
  extraMounts:
  - containerPath: /mnt
    hostPath: ./