apiVersion: apps/v1
kind: Deployment
metadata:
  name: openobserve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openobserve
  template:
    metadata:
      labels:
        app: openobserve
    spec:
      containers:
      - name: openobserve
        image: openobserve
        env:
        - name: ZO_DATA_DIR
          value: "/data"
        - name: ZO_ROOT_USER_EMAIL
          value: "root@example.com"
        - name: ZO_ROOT_USER_PASSWORD
          value: "Complexpass#123"
        ports:
        - containerPort: 5080
---
apiVersion: v1
kind: Service
metadata:
  name: service-openobserve
spec:
  type: NodePort
  ports:
  - port: 5080
    targetPort: 5080
    nodePort: 30004
  selector:
    app: openobserve