apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-a
  template:
    metadata:
      labels:
        app: backend-a
    spec:
      containers:
      - name: backend-a
        image: backend-a
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://service-otel-collector.default.svc.cluster.local:4317"
        ports:
        - containerPort: 8081
        volumeMounts:
        - mountPath: /app
          name: src-volume
      volumes:
      - name: src-volume
        hostPath:
          path: /mnt/service-backend-a
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: service-backend-a
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30001
  selector:
    app: backend-a

