apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: all-tracing
  namespace: istio-system
spec:
  tracing:
  - providers:
    - name: otel-tracing
    randomSamplingPercentage: 100
    customTags:
      "my-attribute":
        literal:
          value: "default-value"